import { IProduct } from './types/Product'

export const sampleProducts: IProduct[] = [
  {
    name: 'Nike Slim Shirt',
    slug: 'nike-slim-shirt',
    image: '../images/p1.jpg',
    category: 'Shirt',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality shirt',
  },
  {
    name: 'Addidas Fit Shirt',
    slug: 'addidas-fit-shirt',
    image: '../images/p2.jpg',
    category: 'Shirt',
    price: 100,
    countInStock: 4,
    brand: 'Addidas',
    rating: 4.2,
    numReviews: 14,
    description: 'high quality Shirt',
  },
  {
    name: 'Lacoste Free Pant',
    slug: 'lacoste-free-pants',
    image: '../images/p3.jpg',
    category: 'Pant',
    price: 78,
    countInStock: 10,
    brand: 'Lacoste',
    rating: 3.8,
    numReviews: 0,
    description: 'high quality Pant',
  },
  {
    name: 'Nike Slim Pant',
    slug: 'nike-slim-pant',
    image: '../images/p4.jpg',
    category: 'Pant',
    price: 200,
    countInStock: 0,
    brand: 'Nike',
    rating: 4.1,
    numReviews: 7,
    description: 'high quality Pant',
  },
]
