export enum ProductsConstants {
  PRODUCTS_FETCH_REQUEST,
  PRODUCTS_FETCH_SUCCESS,
  PRODUCTS_FETCH_FAILED,
  PRODUCT_DETAILS_FETCH_REQUEST,
  PRODUCT_DETAILS_FETCH_SUCCESS,
  PRODUCT_DETAILS_FETCH_FAILED,
}
export enum ThemeConstants {
  SWITCH_MODE_DARK = 'dark',
  SWITCH_MODE_LIGHT = 'light',
}
